In [2]:
area >= 300000
pop >= 2500000

NameError: name 'area' is not defined

In [4]:
import pandas as pd

In [5]:
import pandas as pd

df = pd.read_csv("car_data.csv")
df

,name,company,year,Price,kms_driven,fuel_type
0,Hyundai Santro Xing XO eRLX Euro III,Hyundai,2007,"80,000","45,000 kms",Petrol
1,Mahindra Jeep CL550 MDI,Mahindra,2006,"4,25,000",40 kms,Diesel
2,Maruti Suzuki Alto 800 Vxi,Maruti,2018,Ask For Price,"22,000 kms",Petrol
3,Hyundai Grand i10 Magna 1.2 Kappa VTVT,Hyundai,2014,"3,25,000","28,000 kms",Petrol
4,Ford EcoSport Titanium 1.5L TDCi,Ford,2014,"5,75,000","36,000 kms",Diesel
...,...,...,...,...,...,...
887,Ta,Tara,zest,"3,10,000",NaN,NaN
888,Tata Zest XM Diesel,Tata,2018,"2,60,000","27,000 kms",Diesel
889,Mahindra Quanto C8,Mahindra,2013,"3,90,000","40,000 kms",Diesel
890,Honda Amaze 1.2 E i VTEC,Honda,2014,"1,80,000",Petrol,NaN
891,Chevrolet Sail 1.2 LT ABS,Chevrolet,2014,"1,60,000",Petrol,NaN

In [6]:
df = pd.read_csv("car_data.csv")
df

,name,company,year,Price,kms_driven,fuel_type
0,Hyundai Santro Xing XO eRLX Euro III,Hyundai,2007,"80,000","45,000 kms",Petrol
1,Mahindra Jeep CL550 MDI,Mahindra,2006,"4,25,000",40 kms,Diesel
2,Maruti Suzuki Alto 800 Vxi,Maruti,2018,Ask For Price,"22,000 kms",Petrol
3,Hyundai Grand i10 Magna 1.2 Kappa VTVT,Hyundai,2014,"3,25,000","28,000 kms",Petrol
4,Ford EcoSport Titanium 1.5L TDCi,Ford,2014,"5,75,000","36,000 kms",Diesel
...,...,...,...,...,...,...
887,Ta,Tara,zest,"3,10,000",NaN,NaN
888,Tata Zest XM Diesel,Tata,2018,"2,60,000","27,000 kms",Diesel
889,Mahindra Quanto C8,Mahindra,2013,"3,90,000","40,000 kms",Diesel
890,Honda Amaze 1.2 E i VTEC,Honda,2014,"1,80,000",Petrol,NaN
891,Chevrolet Sail 1.2 LT ABS,Chevrolet,2014,"1,60,000",Petrol,NaN

In [7]:
data  = pd.read_csv("car_data.csv")

In [8]:
data.shape

(892, 6)

In [9]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 892 entries, 0 to 891
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   name        892 non-null    object
 1   company     892 non-null    object
 2   year        892 non-null    object
 3   Price       892 non-null    object
 4   kms_driven  840 non-null    object
 5   fuel_type   837 non-null    object
dtypes: object(6)
memory usage: 41.9+ KB

# Data Cleaning
- Missing Values
      
       Drop
     - Drop the records having missing data
     - Drop the columns having missing data
       
       Fill 
     - Fill the missing values
          - Hard coded value
          - Calculated Values
          - Following or Preceding 
- Duplicate Records
- Outlier

# Missing Values: isna() isnull()

In [10]:
data.isna().sum()

name           0
company        0
year           0
Price          0
kms_driven    52
fuel_type     55
dtype: int64

In [11]:
30,000

(30, 0)

In [12]:
data['kms_driven'].unique()

array(['45,000 kms', '40 kms', '22,000 kms', '28,000 kms', '36,000 kms',
       '59,000 kms', '41,000 kms', '25,000 kms', '24,530 kms',
       '60,000 kms', '30,000 kms', '32,000 kms', '48,660 kms',
       '4,000 kms', '16,934 kms', '43,000 kms', '35,550 kms',
       '39,522 kms', '39,000 kms', '55,000 kms', '72,000 kms',
       '15,975 kms', '70,000 kms', '23,452 kms', '35,522 kms',
       '48,508 kms', '15,487 kms', '82,000 kms', '20,000 kms',
       '68,000 kms', '38,000 kms', '27,000 kms', '33,000 kms',
       '46,000 kms', '16,000 kms', '47,000 kms', '35,000 kms',
       '30,874 kms', '15,000 kms', '29,685 kms', '1,30,000 kms',
       '19,000 kms', nan, '54,000 kms', '13,000 kms', '38,200 kms',
       '50,000 kms', '13,500 kms', '3,600 kms', '45,863 kms',
       '60,500 kms', '12,500 kms', '18,000 kms', '13,349 kms',
       '29,000 kms', '44,000 kms', '42,000 kms', '14,000 kms',
       '49,000 kms', '36,200 kms', '51,000 kms', '1,04,000 kms',
       '33,333 kms', '33,600 kms', '5,600 kms', '7,500 kms', '26,000 kms',
       '24,330 kms', '65,480 kms', '28,028 kms', '2,00,000 kms',
       '99,000 kms', '2,800 kms', '21,000 kms', '11,000 kms',
       '66,000 kms', '3,000 kms', '7,000 kms', '38,500 kms', '37,200 kms',
       '43,200 kms', '24,800 kms', '45,872 kms', '40,000 kms',
       '11,400 kms', '97,200 kms', '52,000 kms', '31,000 kms',
       '1,75,430 kms', '37,000 kms', '65,000 kms', '3,350 kms',
       '75,000 kms', '62,000 kms', '73,000 kms', '2,200 kms',
       '54,870 kms', '34,580 kms', '97,000 kms', '60 kms', '80,200 kms',
       '3,200 kms', '0,000 kms', '5,000 kms', '588 kms', '71,200 kms',
       '1,75,400 kms', '9,300 kms', '56,758 kms', '10,000 kms',
       '56,450 kms', '56,000 kms', '32,700 kms', '9,000 kms', '73 kms',
       '1,60,000 kms', '84,000 kms', '58,559 kms', '57,000 kms',
       '1,70,000 kms', '80,000 kms', '6,821 kms', '23,000 kms',
       '34,000 kms', '1,800 kms', '4,00,000 kms', '48,000 kms',
       '90,000 kms', '12,000 kms', '69,900 kms', '1,66,000 kms',
       '122 kms', '0 kms', '24,000 kms', '36,469 kms', '7,800 kms',
       '24,695 kms', '15,141 kms', '59,910 kms', '1,00,000 kms',
       '4,500 kms', '1,29,000 kms', '300 kms', '1,31,000 kms',
       '1,11,111 kms', '59,466 kms', '25,500 kms', '44,005 kms',
       '2,110 kms', '43,222 kms', '1,00,200 kms', '65 kms',
       '1,40,000 kms', '1,03,553 kms', '58,000 kms', '1,20,000 kms',
       '49,800 kms', '100 kms', '81,876 kms', '6,020 kms', '55,700 kms',
       '18,500 kms', '1,80,000 kms', '53,000 kms', '35,500 kms',
       '22,134 kms', '1,000 kms', '8,500 kms', '87,000 kms', '6,000 kms',
       '15,574 kms', '8,000 kms', '55,800 kms', '56,400 kms',
       '72,160 kms', '11,500 kms', '1,33,000 kms', '2,000 kms',
       '88,000 kms', '65,422 kms', '1,17,000 kms', '1,50,000 kms',
       '10,750 kms', '6,800 kms', '5 kms', '9,800 kms', '57,923 kms',
       '30,201 kms', '6,200 kms', '37,518 kms', '24,652 kms', '383 kms',
       '95,000 kms', '3,528 kms', '52,500 kms', '47,900 kms',
       '52,800 kms', '1,95,000 kms', '48,008 kms', '48,247 kms',
       '9,400 kms', '64,000 kms', '2,137 kms', '10,544 kms', '49,500 kms',
       '1,47,000 kms', '90,001 kms', '48,006 kms', '74,000 kms',
       '85,000 kms', '29,500 kms', '39,700 kms', '67,000 kms',
       '19,336 kms', '60,105 kms', '45,933 kms', '1,02,563 kms',
       '28,600 kms', '41,800 kms', '1,16,000 kms', '42,590 kms',
       '7,400 kms', '54,500 kms', '76,000 kms', '00 kms', '11,523 kms',
       '38,600 kms', '95,500 kms', '37,458 kms', '85,960 kms',
       '12,516 kms', '30,600 kms', '2,550 kms', '62,500 kms',
       '69,000 kms', '28,400 kms', '68,485 kms', '3,500 kms',
       '85,455 kms', '63,000 kms', '1,600 kms', '77,000 kms',
       '26,500 kms', '2,875 kms', '13,900 kms', '1,500 kms', '2,450 kms',
       '1,625 kms', '33,400 kms', '60,123 kms', '38,900 kms',
       '1,37,495 kms', '91,200 kms', '1,46,000 kms', '1,00,800 kms',
       '2,100 kms', '2,500 kms', '1,32,000 kms', 'Petrol'], dtype=object)

In [13]:
data['kms_driven'].isna().sum()

np.int64(52)

### Drop all the missing records
  - dropping rows that have missing values

In [14]:
data.dropna(axis=0)

,name,company,year,Price,kms_driven,fuel_type
0,Hyundai Santro Xing XO eRLX Euro III,Hyundai,2007,"80,000","45,000 kms",Petrol
1,Mahindra Jeep CL550 MDI,Mahindra,2006,"4,25,000",40 kms,Diesel
2,Maruti Suzuki Alto 800 Vxi,Maruti,2018,Ask For Price,"22,000 kms",Petrol
3,Hyundai Grand i10 Magna 1.2 Kappa VTVT,Hyundai,2014,"3,25,000","28,000 kms",Petrol
4,Ford EcoSport Titanium 1.5L TDCi,Ford,2014,"5,75,000","36,000 kms",Diesel
...,...,...,...,...,...,...
883,Maruti Suzuki Ritz VXI ABS,Maruti,2011,"2,70,000","50,000 kms",Petrol
885,Tata Indica V2 DLE BS III,Tata,2009,"1,10,000","30,000 kms",Diesel
886,Toyota Corolla Altis,Toyota,2009,"3,00,000","1,32,000 kms",Petrol
888,Tata Zest XM Diesel,Tata,2018,"2,60,000","27,000 kms",Diesel
889,Mahindra Quanto C8,Mahindra,2013,"3,90,000","40,000 kms",Diesel

In [15]:
# dropping columns that have missing values
data.dropna(axis=1)

                                       name    company  year          Price
0      Hyundai Santro Xing XO eRLX Euro III    Hyundai  2007         80,000
1                   Mahindra Jeep CL550 MDI   Mahindra  2006       4,25,000
2                Maruti Suzuki Alto 800 Vxi     Maruti  2018  Ask For Price
3    Hyundai Grand i10 Magna 1.2 Kappa VTVT    Hyundai  2014       3,25,000
4          Ford EcoSport Titanium 1.5L TDCi       Ford  2014       5,75,000
..                                      ...        ...   ...            ...
887                                      Ta       Tara  zest       3,10,000
888                     Tata Zest XM Diesel       Tata  2018       2,60,000
889                      Mahindra Quanto C8   Mahindra  2013       3,90,000
890                Honda Amaze 1.2 E i VTEC      Honda  2014       1,80,000
891               Chevrolet Sail 1.2 LT ABS  Chevrolet  2014       1,60,000

[892 rows x 4 columns]

In [16]:
# drop only those records where all the values are missing
data.dropna(how='all', axis=0)

,name,company,year,Price,kms_driven,fuel_type
0,Hyundai Santro Xing XO eRLX Euro III,Hyundai,2007,"80,000","45,000 kms",Petrol
1,Mahindra Jeep CL550 MDI,Mahindra,2006,"4,25,000",40 kms,Diesel
2,Maruti Suzuki Alto 800 Vxi,Maruti,2018,Ask For Price,"22,000 kms",Petrol
3,Hyundai Grand i10 Magna 1.2 Kappa VTVT,Hyundai,2014,"3,25,000","28,000 kms",Petrol
4,Ford EcoSport Titanium 1.5L TDCi,Ford,2014,"5,75,000","36,000 kms",Diesel
...,...,...,...,...,...,...
887,Ta,Tara,zest,"3,10,000",NaN,NaN
888,Tata Zest XM Diesel,Tata,2018,"2,60,000","27,000 kms",Diesel
889,Mahindra Quanto C8,Mahindra,2013,"3,90,000","40,000 kms",Diesel
890,Honda Amaze 1.2 E i VTEC,Honda,2014,"1,80,000",Petrol,NaN
891,Chevrolet Sail 1.2 LT ABS,Chevrolet,2014,"1,60,000",Petrol,NaN

In [17]:
data.dropna(how='any', axis=0)

,name,company,year,Price,kms_driven,fuel_type
0,Hyundai Santro Xing XO eRLX Euro III,Hyundai,2007,"80,000","45,000 kms",Petrol
1,Mahindra Jeep CL550 MDI,Mahindra,2006,"4,25,000",40 kms,Diesel
2,Maruti Suzuki Alto 800 Vxi,Maruti,2018,Ask For Price,"22,000 kms",Petrol
3,Hyundai Grand i10 Magna 1.2 Kappa VTVT,Hyundai,2014,"3,25,000","28,000 kms",Petrol
4,Ford EcoSport Titanium 1.5L TDCi,Ford,2014,"5,75,000","36,000 kms",Diesel
...,...,...,...,...,...,...
883,Maruti Suzuki Ritz VXI ABS,Maruti,2011,"2,70,000","50,000 kms",Petrol
885,Tata Indica V2 DLE BS III,Tata,2009,"1,10,000","30,000 kms",Diesel
886,Toyota Corolla Altis,Toyota,2009,"3,00,000","1,32,000 kms",Petrol
888,Tata Zest XM Diesel,Tata,2018,"2,60,000","27,000 kms",Diesel
889,Mahindra Quanto C8,Mahindra,2013,"3,90,000","40,000 kms",Diesel

In [18]:
int(data.shape[1]*.70)

4

In [19]:
int(data.shape[1] *.70)

4

In [20]:
# retain all the records where at least 70% value are valid
data.dropna(axis=0, thresh=int(data.shape[1]*.70)).isnull().sum()

name           0
company        0
year           0
Price          0
kms_driven    52
fuel_type     55
dtype: int64

In [21]:
data.isnull().sum()

name           0
company        0
year           0
Price          0
kms_driven    52
fuel_type     55
dtype: int64

In [22]:
# retain all the records where at least 70% value are valid
data.dropna(axis=1, thresh=int(data.shape[0]*.70)).isnull().sum()

name           0
company        0
year           0
Price          0
kms_driven    52
fuel_type     55
dtype: int64

In [23]:
# drop all those records where ALL value missing in year price or kms_driven
data.dropna(axis=0, subset=['year','Price','kms_driven'],how='all').isna().sum()

name           0
company        0
year           0
Price          0
kms_driven    52
fuel_type     55
dtype: int64

# Filling Missing Data

In [24]:
# fill all the missing value with ahardcoded value like 0 we did, 
data.fillna(0)

,name,company,year,Price,kms_driven,fuel_type
0,Hyundai Santro Xing XO eRLX Euro III,Hyundai,2007,"80,000","45,000 kms",Petrol
1,Mahindra Jeep CL550 MDI,Mahindra,2006,"4,25,000",40 kms,Diesel
2,Maruti Suzuki Alto 800 Vxi,Maruti,2018,Ask For Price,"22,000 kms",Petrol
3,Hyundai Grand i10 Magna 1.2 Kappa VTVT,Hyundai,2014,"3,25,000","28,000 kms",Petrol
4,Ford EcoSport Titanium 1.5L TDCi,Ford,2014,"5,75,000","36,000 kms",Diesel
...,...,...,...,...,...,...
887,Ta,Tara,zest,"3,10,000",0,0
888,Tata Zest XM Diesel,Tata,2018,"2,60,000","27,000 kms",Diesel
889,Mahindra Quanto C8,Mahindra,2013,"3,90,000","40,000 kms",Diesel
890,Honda Amaze 1.2 E i VTEC,Honda,2014,"1,80,000",Petrol,0
891,Chevrolet Sail 1.2 LT ABS,Chevrolet,2014,"1,60,000",Petrol,0

In [25]:
data.isnull().sum()

name           0
company        0
year           0
Price          0
kms_driven    52
fuel_type     55
dtype: int64

# Filling missing data using mean , median , mode , min , max

In [26]:
sum((19,23,1,3,53))/5

19.8

# Central Tendency
-   if there is outlier in data we will use median
-   if there is not outlier in data we will use mean
-   for categorical e will use mode

Bfill(), ffill()

In [27]:
data.fuel_type.isna().sum()

np.int64(55)

In [28]:
data.kms_driven.isna().sum()

np.int64(52)

In [29]:
data.fuel_type.value_counts()

fuel_type
Petrol    440
Diesel    395
LPG         2
Name: count, dtype: int64

In [30]:
data.fuel_type.value_counts(dropna=False)

fuel_type
Petrol    440
Diesel    395
NaN        55
LPG         2
Name: count, dtype: int64

In [31]:
data.fuel_type.mode()

0    Petrol
Name: fuel_type, dtype: object

In [32]:
mode_value = data.fuel_type.mode()[0]
mode_value

'Petrol'

In [33]:
data.fuel_type.fillna(mode_value)

0      Petrol
1      Diesel
2      Petrol
3      Petrol
4      Diesel
        ...
887    Petrol
888    Diesel
889    Diesel
890    Petrol
891    Petrol
Name: fuel_type, Length: 892, dtype: object

In [34]:
data.fuel_type.isnull().sum()

np.int64(55)

In [35]:
data.fuel_type = data.fuel_type.fillna(data.fuel_type.mode()[0])
data.fuel_type

0      Petrol
1      Diesel
2      Petrol
3      Petrol
4      Diesel
        ...
887    Petrol
888    Diesel
889    Diesel
890    Petrol
891    Petrol
Name: fuel_type, Length: 892, dtype: object

In [36]:
data.fuel_type.value_counts(dropna=False)

fuel_type
Petrol    495
Diesel    395
LPG         2
Name: count, dtype: int64

In [37]:
data.fuel_type.isna().sum()

np.int64(0)

In [38]:
data.dropna(subset=['kms_driven'], inplace=True)

In [39]:
data['kms_driven'] = data['kms_driven'].apply(lambda x: x.replace(' kms', '').replace(',', ''))

In [40]:
data.kms_driven.astype(float)

ValueError: could not convert string to float: 'Petrol'

In [41]:
data = data.dropna(subset=['kms_driven'])

In [54]:
mean_value = data[data['kms_driven'] != 'Petrol']['kms_driven'].astype(float).mean()

In [55]:
data['kms_driven'] = data['kms_driven'].apply(lambda x: x.replace('Petrol', str(int(mean_value))))

In [57]:
data.kms_driven = data.kms_driven.astype(float)

In [58]:
data.shape

(840, 6)

In [59]:
data.isna().sum()

name          0
company       0
year          0
Price         0
kms_driven    0
fuel_type     0
dtype: int64

In [61]:
data['Price'] = data['Price'].apply(lambda x: x.replace(',', ''))

In [62]:
data[data['Price'] != 'Ask For Price']

,name,company,year,Price,kms_driven,fuel_type
0,Hyundai Santro Xing XO eRLX Euro III,Hyundai,2007,80000,45000.0,Petrol
1,Mahindra Jeep CL550 MDI,Mahindra,2006,425000,40.0,Diesel
3,Hyundai Grand i10 Magna 1.2 Kappa VTVT,Hyundai,2014,325000,28000.0,Petrol
4,Ford EcoSport Titanium 1.5L TDCi,Ford,2014,575000,36000.0,Diesel
6,Ford Figo,Ford,2012,175000,41000.0,Diesel
...,...,...,...,...,...,...
886,Toyota Corolla Altis,Toyota,2009,300000,132000.0,Petrol
888,Tata Zest XM Diesel,Tata,2018,260000,27000.0,Diesel
889,Mahindra Quanto C8,Mahindra,2013,390000,40000.0,Diesel
890,Honda Amaze 1.2 E i VTEC,Honda,2014,180000,46010.0,Petrol
891,Chevrolet Sail 1.2 LT ABS,Chevrolet,2014,160000,46010.0,Petrol

In [63]:
data = data[data['Price'] != 'Ask For Price']

In [64]:
data['Price'] = data['Price'].astype(float)

In [65]:
data['Price']

0       80000.0
1      425000.0
3      325000.0
4      575000.0
6      175000.0
         ...
886    300000.0
888    260000.0
889    390000.0
890    180000.0
891    160000.0
Name: Price, Length: 819, dtype: float64

In [66]:
data.isna().sum()

name          0
company       0
year          0
Price         0
kms_driven    0
fuel_type     0
dtype: int64

In [67]:
data.year

0      2007
1      2006
3      2014
4      2014
6      2012
       ...
886    2009
888    2018
889    2013
890    2014
891    2014
Name: year, Length: 819, dtype: object

In [69]:
def year_column_transformation(year):
    try:
        result = int(year)
    except:
        result = None
    return result

In [70]:
data['year'] = data['year'].apply(year_column_transformation)

In [71]:
mode = data['year'].mode()
mode

0    2015
Name: year, dtype: int64

In [73]:
data['year'] = data['year'].fillna(mode[0]).astype(int)

In [75]:
data['fuel_type'] = data['fuel_type'].fillna(data['fuel_type'].mode()[0])

In [76]:
data.isna().sum()

name          0
company       0
year          0
Price         0
kms_driven    0
fuel_type     0
dtype: int64

In [77]:
data.to_csv('cleaned_data.csv')

In [78]:
dd# it will not work, bcz we have a string value in the data that can not be 
# converted into float {petrol}
data.kms_driven.str.replace("kms", "").str.replace(",", '').astype(float)

NameError: name 'dd' is not defined

In [85]:
[data.kms_driven == 'Petrol']

[0      False
 1      False
 3      False
 4      False
 6      False
        ...
 886    False
 888    False
 889    False
 890    False
 891    False
 Name: kms_driven, Length: 819, dtype: bool]

In [86]:
data.kms_driven.replace('Petrol', '0', inplace=True)

In [88]:
data['kms_driven']

0       45000.0
1          40.0
3       28000.0
4       36000.0
6       41000.0
         ...
886    132000.0
888     27000.0
889     40000.0
890     46010.0
891     46010.0
Name: kms_driven, Length: 819, dtype: float64

In [91]:
data.kms_driven.replace('Petrol', '0', inplace=True)

In [93]:
data.kms_driven.replace('NaN', '0', inplace=True)

In [97]:
# petrol is treplaced by 0 and kms can be converted into f
data.kms_driven = data.kms_driven.replace("kms","").replace(",",'').astype(float)

In [98]:
data.kms_driven.isna().sum()

np.int64(0)

In [99]:
sns.boxplot(data.kms_driven)

NameError: name 'sns' is not defined